# Generated by Django 5.1 on 2024-08-31 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_foto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
